### PR TITLE
executor config download cleanup

### PR DESCRIPTION
**Pull request by kensipe**
changed cp to mv to move the file into place instead of leaving copies around

### CODE REVIEW

**Comment by kensipe** [comment]
@elingg this seems like a simple way to clean it up.

**Comment by elingg** [comment]
LGTM. Was this tested?

**Comment by kensipe** [comment]
I don't remember... it was just before my vacation.  I have 2 PRs to test this morning... based on feedback if it all tests good.. I'll merge.

**Comment by elingg** [comment]
Sounds good, please merge once tested.

**Pull request merged**
