### PR TITLE
Switching to Gradle

### PR DESCRIPTION
**Pull request by kensipe**
there are a couple of reasons to switch to gradle IMO.

1. it will help with the multi-project structure which will quickly follow this PR
2. it uses the gradlew which makes sure that the correct build tool is present (it bootstraps itself)
3. I want to move the platform specific bash scripts in `bin` into gradle tasks which will be platform agnostic.
4. myriad and other java projects are gradle or I'm moving them that way :)

### CODE REVIEW

**Comment by elingg** [comment]
Hi @kensipe, thanks for this clean up and I am fine with gradle! I will review this ASAP. cc'ing @adam-mesos and @nicgrayson as optional reviewers. I will also be sure to test, including with DCOS before merging.

**Comment by kensipe** [comment]
@elingg any chance to get this merged today?

**Comment by elingg** [comment]
thanks for following up @kensipe! I will do my best to get the review and testing done by tomorrow. I have back to back meetings from noon to 5:30 today. If you have time to test with DCOS before I get to it, let me know and that can save some time.

**Comment by BenWhitehead** [comment]
@elingg you will have to update the builds to account for the new gradle config rather than maven.

**Comment by elingg** [comment]
LGTM, yes, I'm updating the team city build settings @BenWhitehead

**Pull request merged**
