### PR TITLE
Mesos dns integration

### PR DESCRIPTION
**Pull request by abhay-agarwal**
Adding Mesos DNS integration in the interest of not having to reload configurations across the cluster on topology changes

### CODE REVIEW

**Comment by elingg** [comment]
Will need to a much more detailed review later, but a couple of things right off the bat. The build needs to succeed. The readme needs to describe how to turn mesos DNS on and off. Instead of sleeping when checking for mesos DNS please use a timer object. You can see an example of this in the health check branch.

**Comment by elingg** [comment]
Thanks for following up and making more changes @abhay-agarwal ! A follow up on my prior note, please remove the README from the conf folder since that has the Mesos DNS info. One central readme should be sufficient for now and we would want this information to show up on the main page where you have it.  Also, please use a Java Timer instead of those messy sleep calls when checking to see if Mesos DNS is working. We will be checking in the state machine changes ASAP (either today or tomorrow, https://github.com/mesosphere/hdfs/pull/59) so it may help to rebase with them so that the tasks are started in a clean way.

**Comment by abhay-agarwal** [comment]
Sure, though I would rebase the #59 changes to the master branch (with my merged PR #70) first, just so that i'm not rebase a huge list of changes. This PR is based against the master branch as it currently stands. I'll pull the extra README and transfer the info to the main one.

**Comment by elingg** [comment]
@abhay-agarwal, sounds great and thanks for your patience on this. After review, we're merging https://github.com/mesosphere/hdfs/pull/72 so you can rebase with master once it's merged.

**Comment by kensipe** [comment]
@abhay-agarwal nice work

**Pull request closed without merging**
