### PR TITLE
Dcos builds

### PR DESCRIPTION
**Pull request by kensipe**
It is now possible to do a DCOS build from the build script.   `./bin/build-hdfs dcos`

readmes updated and the conf directories were cleaned up.

### CODE REVIEW

**Comment by elingg** [comment]
hi @kensipe, I prefer to have only the files in use under conf/ and have a separate example conf directory with different examples. Otherwise, it's confusing for the user. I think this build should copy over the example conf into conf if user wants to build using the dcos option.

**Comment by kensipe** [comment]
I can put the example dir back.. but I don't want to "dirty" the project by copying over files into the git managed project.  A build shouldn't result in a scenario where a git sees changes to the underlying project.   As soon as that view is the target, it made sense to me to have all the confs as being symmetrical or even parity.    If we want to copy files in and out of the `/conf` directory, then we will want that directory to be ignored from a git perspective. (which may be confusing on the first clone of the repo).

**Comment by kensipe** [comment]
@elingg this is now the way we last discussed (realizing that there is still thinking to do on this)

1. the /conf directory is an ignore dir and not under git
2. if the /conf is missing on a build, it will be created with the original default standard mesos config
3. there is a new ./bin/configure-hdfs which will by default create the original configuration
4. with a `./bin/configure-hdfs dcos` it will remove the xml files in /conf and will copy in the dcos

upsides, if you have your own configuration, it can be put in /conf and all is go

downside, if you call configure-hdfs, it will delete files in the /conf so if you had changes or your own files that feels bad.   I could add a confirmation if desired.   I'll wait for feedback at this point.

**Comment by elingg** [comment]
Thanks, @kensipe. I've spent some time thinking about this and I think we need to clean up our configuration to use either environment variables or command line args and properly pass changes from scheduler to the executor. User should have to easily change the config only once and it should be much simpler for the users. I am thinking of something similar to this commit: https://github.com/mesosphere/hdfs/pull/123. I think this would be a higher priority than creating an automated DCOS build. We already have a branch for this as it is.

**Comment by kensipe** [comment]
sounds good.  I'll kill this PR and will assume that we will have a JIRA for the additional work.

**Pull request closed without merging**
