### PR TITLE
Switch default data dir from `/tmp` to `/var/lib`.

### PR DESCRIPTION
**Pull request by brndnmtthws**
cc @elingg @abhay-agarwal

### CODE REVIEW

**Comment by adam-mesos** [comment]
@brndnmtthws Can you update the docs as well, please?

**Comment by brndnmtthws** [comment]
I don't see any references to that in the docs. What would you like to see?

**Comment by elingg** [comment]
@brndnmtthws you also need to update https://github.com/mesosphere/hdfs/blob/master/hdfs-commons/src/main/java/org/apache/mesos/hdfs/config/HdfsFrameworkConfig.java for consistent configs.

**Comment by brndnmtthws** [comment]
@elingg done!

**Comment by adam-mesos** [comment]
Looks great! We'll also want to get @joel-hamill to update the reference at the end of https://docs.mesosphere.com/services/hdfs/
:rocket:

**Comment by joel-hamill** [comment]
@adam-mesos Got it, should be merged this evening.

**Comment by adam-mesos** [comment]
One problem with `/var/lib` is that you have to run the hdfs commands as root, or another privileged user to be able to write there. Any user can launch hdfs out of the box if it's writing to `/tmp`.

**Comment by brndnmtthws** [comment]
@adam-mesos I guess the question is: what's more important, reducing the risk of data loss? or the inconvenience of having to configure things?

I'd argue that avoiding data loss after a reboot is more important.

**Comment by adam-mesos** [comment]
I'd argue that having easy startup instructions that work out of the box is most important. Ideally that also doesn't write to /tmp. But we'll need to walk through the getting started flow to see how to make that work smoothly. Maybe we just tell them to launch the scheduler as root, so that the hdfs DNs can write to /var/lib. I'm wary of merging this in until we know that a naive user has enough info to not get screwed.

**Comment by elingg** [comment]
Just so you know on DCOS, we do configure it under /var/lib. It is a configurable value obviously. The question is what it makes sense to default to. I see Adam's point that we want to make it easy for users to get it up and running without errors so I'm inclined to use /tmp/ as a default value, but I'm definitely open to discussion here. Note that we will be using Persistent Volumes so this code will eventually be deprecated!

**Comment by elingg** [comment]
Any thoughts @gabrielhartmann, @kensipe?

**Comment by gabrielhartmann** [comment]
I think having the framework setup to avoid dataloss by default is important enough that the inconvenience of requiring use of a privileged account is more than adequately off-set.

**Comment by elingg** [comment]
By comparison, Cassandra writes by default into the sandbox. We really need to fix this issue with persistent volumes, but what do we do in the short term?

**Comment by kensipe** [comment]
I agree with @gabrielhartmann avoiding data loss is "expected" behavior of this service.  Needing to configure the service is also "expected".   still reviewing code but the concept is better IMO.

**Comment by elingg** [comment]
thanks all for the feedback. Ok, @kensipe, if you could test this one as well (on non DCOS) and then merge, that would be great.

**Comment by kensipe** [comment]
roger that... testing in 3... 2... 1...

**Comment by kensipe** [comment]
@brndnmtthws @elingg this change seems to fail... all nodes stage and run until data nodes.   Data nodes never stage...  going for a retest now.

**Comment by kensipe** [comment]
well damn!   Retesting seemed to work on a fresh cluster.    The previous cluster did have hdfs installed multiple times and what I thought was properly uninstalled...   I will test 1 more time and assume a dirty cluster was the issue if all is good.

based on that... I will merge.   2 tests to go... 1 more on dcos and 1 on GCE.

**Comment by elingg** [comment]
Nice, thanks @kensipe!

**Comment by kensipe** [comment]
multiple dcos tests and 1 GCE tests... all looks good.  It needs to be rebased to master

**Pull request merged**
