### PR TITLE
cfg_env_vars_override

### PR DESCRIPTION
**Pull request by dmitrypekar**
Hi.

This PR allows to override params from mesos-site.xml via env vars.
Please review & merge.

### CODE REVIEW

**Comment by kensipe** [comment]
Good addition!  Thanks!

**Comment by kensipe** [comment]
just be aware there is a danger to this... it is possible that a process (like the scheduler) was started with an ENV var which isn't passed to the executors resulting in a bad configuration.  However I like this addition and will work it into some config changes I'm working on.

additionally I would love to see testing around this... merging as is and will add tests.

**Comment by elingg** [comment]
Please add a few docs for this too @dmitrypekar so users know how to use this. Perhaps a sample Marathon file would be useful (assuming it works and is tested).

**Comment by elingg** [comment]
Note we can fix our DCOS config to allow us to do more configuration with environment variables. We have a lot of hard coding there that needs to be fixed. Of course we need to appropriately test.

**Comment by dmitrypekar** [comment]
This is tested. Sure, will add doc changes as a separate PR.

**Comment by elingg** [comment]
@dmitrypekar, @kensipe already added the docs in a subsequent PR :) Maybe an example marathon.json would be useful though with environment variables set.

**Pull request merged**
