### PR TITLE
Add secondaryDataDir to config model. Use a second data directory.

### PR DESCRIPTION
**Pull request by rmvz**

### CODE REVIEW

**Comment by kensipe** [comment]
@rmvz is this a situation where we actually had the config option and didn't actually use it?   It appears so.    Did you test this?

The only thing I don't like about this solution is my expectation is that this should be an opt-in option however the default value for `mesos.hdfs.secondary.data.dir` is `/var/run/hadoop-hdfs` and should probably be nothing.    It seems to require a change to `HdfsFrameworkConfig` and `mesos-site.xml`

**Comment by rmvz** [comment]
@kensipe Yes, we are using this in our internal build to have datanodes use 2 different mount points for data.

The only reference to secondary data dir I see in hdfs-site.xml is the comment for the domain socket path property[1] so this may not have been the original purpose of the secondary data dir? In any case I agree that having non-empty default value is not good but I wanted to run this by you in case it is required for domain socket property, in that case, I would suggest creating a separate property for domain socket dir and leave secondary data dir for data.

[1] https://github.com/mesosphere/hdfs/blob/master/conf/hdfs-site.xml#L172

**Comment by rmvz** [comment]
It actually seems that the only link between dfs.domain.socket.path and mesos.hdfs.secondary.data.dir is that the directory needs to exist for the domain socket to be created so even more so I would create a separate property for that.

**Comment by elingg** [comment]
@kensipe, the secondary data dir is most definitely being used. We need to be very careful not to make assumptions and break the code. mesos.hdfs.secondary.data.dir is being used for domain socket path so probably it would be best if it were renamed accordingly.  Then we could have a second property for secondary data dir as @rmvz mentioned

**Comment by kensipe** [comment]
nice turn around... I'm in the middle of something but will look shortly... quick glance looks good.

**Comment by elingg** [comment]
Cool, first glance also looks great. @kensipe and I talked and he will create another PR to pass the socket path as an environment variable to be used in hdfs-site.xml so we don't declare this variable in both mesos-site.xml and hdfs-site.xml.

**Comment by kensipe** [comment]
LGTM and tested!   merging and will make the changes @elingg mentioned.  Thanks for the contribution and such a quick response.

**Comment by rmvz** [comment]
Glad to help!

**Pull request merged**
