### PR TITLE
moved dependencies to the correct projects.

### PR DESCRIPTION
**Pull request by kensipe**
this should reduce the size of the executor uber jar

### CODE REVIEW

**Comment by kensipe** [comment]
@elingg not much to review... simple dependency clean.  marking off the tech debt.

**Comment by elingg** [comment]
Thanks @kensipe, nice to do a simple review! Just confirming joda-time:joda-time and com.google.guava:guava are unused dependencies? Or they are encapsulated elsewhere?

**Comment by kensipe** [comment]
regarding the removed dependencies...  I tested without them.  They don't seem to be used.  If they are used "encapsulated" then that should be transitive dependencies for which they will show up without the explicit declaration.  I think we are good.

**Comment by elingg** [comment]
Cool, makes sense. LGTM!

**Pull request merged**
