### PR TITLE
Removing extra copied hadoop dirs

### PR DESCRIPTION
**Pull request by kensipe**
removed the extra dirs copied over in the build process.  this will remove confusing extra config files

### CODE REVIEW

**Comment by kensipe** [comment]
@elingg should be a simple review

**Comment by elingg** [comment]
@kensipe this is a very simple review. The part where we remove 2 out of 3 copies from the sandbox, will that be a separate PR?

**Comment by elingg** [comment]
Ok, should be good to go, @kensipe. Was this tested on your Mesos cluster and DCOS?

**Comment by kensipe** [comment]
tested... and merging

**Pull request merged**
